language: python
puthon: 3.8
script: 
  - cd PythonApplication1
  - pytest
  - cd ..
deploy:
  provider: releases
  pre-release: true
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    repo: Timanchik/LB6
    branch: dev
    tags: true

